# Use the official Python image from the Docker Hub
FROM python:3.8-slim-buster

# Set the working directory
WORKDIR /code

# Copy the requirements file into the image
COPY requirement.txt .

# Install the dependencies
RUN pip install -r requirement.txt

# Copy the rest of the code into the image
COPY . .

# Run migrations and start the Django development server
CMD ["python", "manage.py", "migrate"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
